declare let css: string;
declare const sc: string[];
declare const pt: string[];
declare const colors: string[];
declare const mini = "mini-scrollbar";
declare const hidden = "mini-scrollbar-hidden";
declare const scrollbar: string;
declare const tr = "--move-x: 0; --move-y: 0; --rotate: 0; --skew-x: 0; --skew-y: 0; --scale-x: 1; --scale-y: 1; transform: translateX(var(--move-x)) translateY(var(--move-y)) rotate(var(--rotate)) skewX(var(--skew-x)) skewY(var(--skew-y)) scaleX(var(--scale-x)) scaleY(var(--scale-y));";
declare const fm: any;
declare let root: string;
declare let md: string;
declare const mknow: (n: string, v: string) => void;
declare const mkhover: (n: string, v: string) => void;
declare const mkfocus: (n: string, v: string) => void;
declare const mkfocusGroup: (n: string, v: string) => void;
declare const mkactive: (n: string, v: string) => void;
declare const mkactiveGroup: (n: string, v: string) => void;
declare function addEl(str: string): void;
declare function mkEle(): void;
declare function render(mk: any): void;
declare const mkList: ((n: string, v: string) => void)[];
declare const mkListLength: number;
declare let mi: number;
declare function timoutRun(): void;
