declare let css: string;
declare const sc: string[];
declare const pt: string[];
declare const mini = "mini-scrollbar";
declare const hidden = "mini-scrollbar-hidden";
declare const miniHidden: string;
declare const scrollbar: string;
declare const fm: any;
declare const colors: string[];
declare let root: string;
declare let max: string;
declare let min: string;
declare const mknow: (n: string, v: string) => void;
declare const mkhover: (n: string, v: string) => void;
declare const mkactive: (n: string, v: string) => void;
declare function mkEle(): void;
declare function start(mk: any): void;
