declare let css: string;
declare const unit: string[];
declare const scUnit: string[];
declare const fsUnit: string[];
declare const mini = "mini-scrollbar";
declare const hidden = "mini-scrollbar-hidden";
declare const miniHidden: string;
declare const scrollbar: string;
declare const fm: any;
declare const colors: string[];
declare let root: string;
declare const l1 = 20;
declare const l2: number;
declare const l3: number;
declare function vl(fn: (i: number) => any): void;
declare let max: string;
declare let min: string;
declare const mknow: (n: string, v: string) => void;
declare const mkhover: (n: string, v: string) => void;
declare const mkactive: (n: string, v: string) => void;
declare function mkEle(): void;
declare function start(mk: any): void;
