export const classCache: { [key: string]: boolean } = {};
export const atomCache: { [key: string]: boolean } = {};

export const alias: { [key: string]: string } = {
  d: "display",
  bg: "background",
  bgi: "background-image",
  gap: "grid-gap",
  pos: "position",
  ta: "text-align",
  area: "display:grid; grid-area",
  "areas": "display:grid; grid-template-areas",
  "rows": "display:grid; grid-template-rows",
  "cols": "display:grid; grid-template-columns",
  "wrap": "flex-wrap",
  "flex": "flex-direction",
  "jc": "justify-content",
  "ji": "justify-items",
  "js": "justify-self",
  "ac": "align-content",
  "ai": "align-items",
  "as": "align-self",
  "pc": "place-content",
  "pi": "place-items",
  "ps": "place-self",
  z: "z-index",
  c: "color",
  "shadow": "box-shadow",
  radius: "border-radius",
  flow: "overflow",
  b: "border",
  br: "border-right",
  bt: "border-top",
  bb: "border-bottom",
  bl: "border-left",
  p: "padding",
  pr: "padding-right",
  pt: "padding-top",
  pb: "padding-bottom",
  pl: "padding-left",
  m: "margin",
  mr: "margin-right",
  mt: "margin-top",
  mb: "margin-bottom",
  ml: "margin-left",
  h: "height",
  "min-h": "min-height",
  "max-h": "max-height",
  w: "width",
  "min-w": "min-width",
  "max-w": "max-width",
  "font": "font-size",
  "weight": "font-weight",
  "family": "font-family",
  "flow-x": "overflow-x",
  "flow-y": "overflow-y",
};
