export const classCache: { [key: string]: boolean } = {};
export const atomCache: { [key: string]: boolean } = {};

// export const alias: { [key: string]: string } = {
//   // d: "display",
//   // bg: "background",
//   // bgi: "background-image",
//   // gap: "grid-gap",
//   // // pos: "position",
//   // area: "grid-area",
//   // "areas": "grid-template-areas",
//   // "rows": "grid-template-rows",
//   // "cols": "grid-template-columns",
//   // "wrap": "flex-wrap",
//   // "shadow": "box-shadow",
//   // radius: "border-radius",
//   // b: "border",
//   // br: "border-right",
//   // bt: "border-top",
//   // bb: "border-bottom",
//   // bl: "border-left",
//   // p: "padding",
//   // pr: "padding-right",
//   // pt: "padding-top",
//   // pb: "padding-bottom",
//   // pl: "padding-left",
//   // m: "margin",
//   // mr: "margin-right",
//   // mt: "margin-top",
//   // mb: "margin-bottom",
//   // ml: "margin-left",
//   // h: "height",
//   // "min-h": "min-height",
//   // "max-h": "max-height",
//   // w: "width",
//   // "min-w": "min-width",
//   // "max-w": "max-width",
//   // "font": "font-size",
//   // "weight": "font-weight",
//   // "family": "font-family",
// };
