export const pseudoElements = {
  after: true,
  backdrop: true,
  before: true,
  cue: true,
  "first-letter": true,
  "first-line": true,
  "grammar-error": true,
  "marker": true,
  "placeholder": true,
  "selection": true,
  "slotted": true,
  "spelling-error": true,
};

export const pseudoClasses = {
  active: true,
  "any-link": true,
  "blank": true,
  "checked": true,
  "current": true,
  "default": true,
  "defined": true,
  "disabled": true,
  "drop": true,
  "empty": true,
  "enabled": true,
  "first": true,
  "first-child": true,
  "first-of-type": true,
  "fullscreen": true,
  "future": true,
  "focus": true,
  "focus-visible": true,
  "focus-within": true,
  "host": true,
  "hover": true,
  "indeterminate": true,
  "in-range": true,
  "invalid": true,
  "last-child": true,
  "last-of-type": true,
  "left": true,
  "link": true,
  "local-link": true,
  "only-child": true,
  "only-of-type": true,
  "optional": true,
  "out-of-range": true,
  "past": true,
  "placeholder-shown": true,
  "read-only": true,
  "read-write": true,
  "required": true,
  "right": true,
  "root": true,
  "scope": true,
  "target": true,
  "target-within": true,
  "user-invalid": true,
  "valid": true,
  "visited": true,
};

// export const pseudoAll = Object.assign({}, pseudoElements, pseudoClasses);
