import React from "react";
import DocumentLayout, {
  DocumentlayoutProps,
} from "pages/components/DocumentLayout";

export default ({ children }: DocumentlayoutProps) => {
  return <DocumentLayout list={list} children={children} />;
};

const list = [
  { head: "Document" },
  { title: "Why Flavorcss?", url: "/" },
  { title: "对比其他原子类CSS库", url: "/document/vs-other" },
  { head: "入门" },
  { title: "安装", url: "/document/install" },
  { title: "浏览器支持", url: "/document/browser" },
  { title: "SSR 支持", url: "/document/ssr" },
  { head: "核心概念" },
  { title: "运行机制", url: "/document/operating" },
  { title: "原子类", url: "/document/atomic-class" },
  { title: "响应式设计", url: "/document/responsive-design" },
  { title: "伪类", url: "/document/pseudo-class" },
  { title: "提取组件", url: "/document/use-components" },
  { head: "Config" },
  { title: "Units", url: "/document/util" },
  { title: "Colors", url: "/document/colors" },
  { title: "自定义配置", url: "/document/config" },
  { head: "Layout" },
  { title: "Container", url: "/document/container" },
  { title: "Box Sizing", url: "/document/box-sizing" },
  { title: "Display", url: "/document/display" },
  { title: "Float", url: "/document/float" },
  { title: "Clear", url: "/document/clear" },
  { title: "Object Fit", url: "/document/object-fit" },
  { title: "Object Position", url: "/document/object-position" },
  { title: "Overflow", url: "/document/overflow" },
  { title: "Position", url: "/document/position" },
  { title: "Top/Right/Bottom/Left", url: "/document/top-right-bottom-left" },
  { title: "Visibility", url: "/document/visibility" },
  { title: "Z-index", url: "/document/z-index" },
  { head: "FlexBox" },
  { title: "Flex Direction", url: "/document/flex-direction" },
  { title: "Flex Wrap", url: "/document/flex-wrap" },
  { title: "Justify Content - Align Items", url: "/document/justify" },
  { title: "Align Content", url: "/document/align-content" },
  { title: "Align Self", url: "/document/align-self" },
  { title: "Flex", url: "/document/flex" },
  { title: "Order", url: "/document/order" },
  { head: "Grid" },
  { title: "Grid Template Columns", url: "/document/grid-template-columns" },
  { title: "Grid Template Rows", url: "/document/grid-template-rows" },
  { title: "Grid Column Start End", url: "/document/grid-column-start-end" },
  { title: "Grid Row Start/End", url: "/document/grid-row-start-end" },
  { title: "Gap", url: "/document/gap" },
  { title: "Grid Auto Flow", url: "/document/grid-auto-flow" },
  { head: "Spaces" },
  { title: "Padding", url: "/document/padding" },
  { title: "Margin", url: "/document/margin" },
  { head: "Sizing" },
  { title: "Width", url: "/document/width" },
  { title: "Height", url: "/document/height" },
  { head: "font/text" },
  { title: "Font Family", url: "/document/font-family" },
  { title: "Font Size", url: "/document/font-size" },
  { title: "Font Smoothing", url: "/document/font-smoothing" },
  { title: "Font Style", url: "/document/font-style" },
  { title: "Font Weight", url: "/document/font-weight" },
  { title: "Letter Spacing", url: "/document/letter-spacing" },
  { title: "Line Height", url: "/document/line-height" },
  { title: "List Style Type", url: "/document/list-style-type" },
  { title: "List Style Position", url: "/document/list-style-position" },
  { title: "Text Align", url: "/document/text-align" },
  { title: "Text Decoration", url: "/document/text-decoration" },
  { title: "Text Transform", url: "/document/text-transform" },
  { title: "Vertical Align", url: "/document/vertical-align" },
  { title: "Whitespace", url: "/document/whitespace" },
  { title: "Word Break", url: "/document/word-break" },
  { head: "Background" },
  { title: "Background Attachment", url: "/document/background-attachment" },
  { title: "Background Position", url: "/document/background-position" },
  { title: "Background Repeat", url: "/document/background-repeat" },
  { title: "Background Size", url: "/document/background-size" },
  { head: "Border" },
  { title: "Border Radius", url: "/document/border-radius" },
  { title: "Border Width", url: "/document/border-width" },
  { title: "Border Style", url: "/document/border-style" },
  { title: "Outline Width", url: "/document/outline-width" },
  { title: "Outline Style", url: "/document/outline-style" },
  { head: "Table" },
  { title: "Border Collapse", url: "/document/border-collapse" },
  { title: "Table Layout", url: "/document/table-layout" },
  { head: "Effect" },
  { title: "Box Shadow", url: "/document/box-shadow" },
  { title: "Opacity", url: "/document/opacity" },
  { head: "Transition" },
  { title: "Transition Property", url: "/document/transition-property" },
  {
    title: "Transition Timing Function",
    url: "/document/transition-timing-function",
  },
  { title: "Transition Delay", url: "/document/transition-delay" },
  { title: "Animation Spin", url: "/document/animation-spin" },
  { head: "Transforms" },
  { title: "Scale", url: "/document/scale" },
  { title: "Rotate", url: "/document/rotate" },
  { title: "Move", url: "/document/translate" },
  { title: "Will Change", url: "/document/will-change" },
  { title: "Skew", url: "/document/skew" },
  { title: "Transform Origin", url: "/document/transform-origin" },
  { head: "Interactivity" },
  { title: "Appearance", url: "/document/appearance" },
  { title: "Cursor", url: "/document/cursor" },
  { title: "Pointer Events", url: "/document/pointer-events" },
  { title: "Resize", url: "/document/resize" },
  { title: "User Select", url: "/document/user-select" },
  { head: "Svg" },
  { title: "Fill", url: "/document/fill" },
  { title: "Stroke", url: "/document/stroke" },
  { title: "Stroke Width", url: "/document/stroke-width" },
  { head: "Accessibility" },
  { title: "Screen Readers", url: "/document/screen-readers" },
];
